# https://golangci-lint.run/usage/configuration/
run:
  tests: false
  concurrency: 4
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - gofumpt
    - gocyclo
    - goimports
    - gosimple
    - unused
    - prealloc
    - misspell
    - exhaustruct
    - unparam
    - nolintlint
  disable:
    - errcheck

linters-settings:
  unused:
    field-writes-are-uses: true
    post-statements-are-reads: false
    exported-fields-are-used: true
    parameters-are-used: true
    local-variables-are-used: false
  misspell:
    locale: US
  revive:
    severity: warning
  exhaustruct:
    exclude:
      - '^github\.com/redis/go-redis/v9\.Options$'
      - '^github\.com/gorilla/websocket\.Upgrader$'
      - '^net/http\.Server$'
      - '^log/slog\.HandlerOptions$'

issues:
  max-same-issues: 3
  max-issues-per-linter: 20

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true