services:
  redis:
    image: redis:7.4.1-alpine3.20
    container_name: ${REDIS_HOST}
    entrypoint: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: ["CMD", "redis-cli","-p", "${REDIS_PORT}","ping"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - sharetube

  server:
    container_name: sharetube-server
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - sharetube

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/ssl:ro # For SSL certificates
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     redis:
  #       condition: service_started
  #     server:
  #       condition: service_started
  #   networks:
  #     - sharetube

networks:
  sharetube: