services:
  redis:
    image: redis:7.4.1-alpine3.20
    container_name: sharetube-redis
    entrypoint: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - sharetube

  server:
    container_name: sharetube-server
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - sharetube

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - /var/www/certbot:/var/www/certbot
  #   depends_on:
  #     - app

networks:
  sharetube: