name: Docker Image CI

on:
  push:
    branches: [main] # Trigger on pushes to the main branch
  pull_request:
    branches: [main] # Trigger on pull requests targeting the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: . # Current directory as build context
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ github.sha }} # Tag with the commit SHA
          build-args: | # optional build arguments
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          platforms: linux/amd64,linux/arm64 # support multiple architectures if needed

      - name: Save buildx cache
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: buildx-cache
          path: /tmp/.buildx-cache-new
